### 生产环境配置
spring:
  application:
    name: system
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.42.143.130:3306/iot_system?serverTimezone=UTC
    username: root
    password: zhanwei
  cloud:
    consul:
      host: gateway.iwiya.com
      port: 32530
      enabled: true
      discovery:
        health-check-path: /system/actuator/health
        prefer-ip-address: true
  ### 调用追踪配置
  zipkin:
    base-url: http://121.42.143.130:9410
  sleuth:
    sampler:
      percentage: 1.0

cassandra:
  host: 118.31.46.174
  port: 9042
  keyspace: demo